version: '3.9'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
  redis:
    image: redis:alpine
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    container_name: redis
    ports:
      - "6379:6379"
    restart:
      always
volumes:
  mongodb: